namespace ReviewApplication.Data.Migrations
{
    using Core.Domain;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<ReviewApplication.Data.Infrastructure.ReviewApplicationDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(ReviewApplication.Data.Infrastructure.ReviewApplicationDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data. E.g.
            //
            //    context.People.AddOrUpdate(
            //      p => p.FullName,
            //      new Person { FullName = "Andrew Peters" },
            //      new Person { FullName = "Brice Lambson" },
            //      new Person { FullName = "Rowan Miller" }
            //    );
            //
            //------------------------------------------------------------------------

            //TODO: Set all the proper ID's and Attributes


            //Build 20 Users


            //Build 10 companies || => 7 Verified, 3 Un-Verified
            context.Companies.AddOrUpdate(x => x.CompanyID,


            #region

                //Company 1
                new Company
                {
                    CompanyID = 1,
                    UserID = 1,
                    IsArchived = false,
                    Verified = false,
                    CompanyName = "Joe Schmoes Lead Company",
                    Address1 = "101 Wonder Way",
                    Address2 = "Suite: 290",
                    State = "CA",
                    City = "Los Angeles",
                    Zip = "90036",
                    TelephoneNumber = "5553331234",
                    OtherTelephoneNumber = "5551231234",
                    EmailAddress = "Joe@leads.com",
                    SkypeHandle = "LeadCo",
                    WebsiteURL = "http://www.leadcompany.com",
                    PictureLogoURL = "https://lh5.ggpht.com/E3EDtjhawNHXNOhnid79xqMofjwy6wIciqHC_-Xe77F9HhPfDOYaJLFTyGBYsDeHvQ=w300",
                    Bio = "The best lead company ever.  Like a pheonix we rise from the ashes.",
                    LeadNotes = "Our leads are generated by highly trained tele-sales professionals",
                    PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                    //Payment Area  || Stripe?
                    AcceptsCredit = true,
                    CreditComments = "We accept Credit",
                    AcceptsDebit = true,
                    DebitComments = "We accept Debit",
                    AcceceptsAmericanExpress = true,
                    AmericanExpressComments = "We accept American Express",
                    AcceptsPaypal = true,
                    PaypalEmailAddress = "joeLeads@leads.com",
                    PaypalComments = "We accept Paypal",
                    AcceptsMoneyOrder = true,
                    MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                    AcceptsVenmo = true,
                    VenmoComments = "Maximum transaction amount $675",
                    VenmoHandle = "JoesLeadsNow",
                    //Company Rating Depends on ReviewPosts

                },

                 //Company 2 || Unverified
                 new Company
                 {
                     CompanyID = 2,
                     UserID = 3,
                     IsArchived = false,
                     Verified = false,
                     CompanyName = "All Star Leads Company",
                     Address1 = "111 Hollwood Blvd",
                     Address2 = "Suite: 880",
                     State = "CA",
                     City = "Los Angeles",
                     Zip = "90036",
                     TelephoneNumber = "5556667894",
                     OtherTelephoneNumber = "5557891234",
                     EmailAddress = "leads@allstarleads.com",
                     SkypeHandle = "AllStarLeads",
                     WebsiteURL = "http://www.AllStarleads.com",
                     PictureLogoURL = "http://design.ubuntu.com/wp-content/uploads/ubuntu-logo32.png",
                     Bio = "All Star Leads Company.  Our leads are 5-star!",
                     LeadNotes = "All of our leads are organic and come with a contact gurantee!",
                     PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                     //Payment Area  || Stripe?
                     AcceptsCredit = true,
                     CreditComments = "We accept Credit",
                     AcceptsDebit = true,
                     DebitComments = "We accept Debit",
                     AcceceptsAmericanExpress = true,
                     AmericanExpressComments = "We accept American Express",
                     AcceptsPaypal = true,
                     PaypalEmailAddress = "leads@allstarleads.com",
                     PaypalComments = "We accept Paypal",
                     AcceptsMoneyOrder = true,
                     MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                     AcceptsVenmo = true,
                     VenmoComments = "We accept Venmo!",
                     VenmoHandle = "AllStarLeads",

                     //Company Rating Depends on ReviewPosts
                 },

                 //Company 3
                 new Company
                 {

                 },

                 //Company 4
                 new Company
                 {

                 },

                 //Company 5
                 new Company
                 {

                 },

                 //Company 6
                 new Company
                 {

                 },

                 //Company 7
                 new Company
                 {

                 },

                 //Company 8
                 new Company
                 {

                 },

                 //Company 9
                 new Company
                 {

                 },

                 //Company 10
                 new Company
                 {

                 }


                 #endregion
                );

            //Build 10 Insurance Agents || => 5 Verified, 5 Un-Verified
            context.InsuranceAgents.AddOrUpdate(x => x.InsuranceAgentID,

            #region

                //InsuranceAgent 1
                new InsuranceAgent
                {

                },

                //InsuranceAgent2
                new InsuranceAgent
                {

                },
                //InsuranceAgent 3
                new InsuranceAgent
                {

                },
                //InsuranceAgent 4
                new InsuranceAgent
                {

                },
                //InsuranceAgent 5
                new InsuranceAgent
                {

                },
                //InsuranceAgent 6 
                new InsuranceAgent
                {

                },
                //InsuranceAgent 7
                new InsuranceAgent
                {

                },
                //InsuranceAgent 8
                new InsuranceAgent
                {

                },
                //InsuranceAgent 9
                new InsuranceAgent
                {

                },

                //InsuranceAgent 10
                new InsuranceAgent
                {

                }


#endregion
                );
    


            //Build Industries


            //Build CompanyIndustries


            //Build InsuranceAgentIndustries


            //Build LeadProducts
            
            //Build LeadTransactions

            //Build Comments

            //Build ReviewPosts






        }




    }
}
