using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using ReviewApplication.Core.Domain;
using ReviewApplication.API.Controllers;
using ReviewApplication.Core.Infrastructure;
using ReviewApplication.Core.Repository;

namespace ReviewApplication.API.Test.ReviewApplication
{
    [TestClass]
    public class CompaniesControllerTests
    {
        private Mock<ICompanyRepository> _companyRepositoryMock;
        private Mock<IUnitOfWork> _unitOfWork;
        private CompaniesController _controller;
        private Company[] _companies;



        [TestInitialize]
        public void Initialize()
        {
            //Setup Automapper
            WebApiConfig.SetupAutomapper();

            //Set up Repositories
            _companyRepositoryMock = new Mock<ICompanyRepository>();

            //Set Data in Repositories
            _companies = new[]
            {
                new Company
                {
                     CompanyID = 1,
                     UserID = 1,
                    IsArchived = false,
                    IndustryID = 1,
                     CompanyName = "Joe Schmoes Lead Company",
                     Address1 = "101 Wonder Way",
                     Address2 = "Suite: 290",
                     State = "CA",
                     City = "Los Angeles",
                     Zip = "90036",
                     TelephoneNumber = "5553331234",
                     OtherTelephoneNumber = "5551231234",
                     EmailAddress  = "Joe@leads.com",
                     SkypeHandle = "LeadCo",
                WebsiteURL = "http://www.leadcompany.com",
                     PictureLogoURL = "https://lh5.ggpht.com/E3EDtjhawNHXNOhnid79xqMofjwy6wIciqHC_-Xe77F9HhPfDOYaJLFTyGBYsDeHvQ=w300",
                     Bio = "The best lead company ever.  Like a pheonix we rise from the ashes.",
                     LeadNotes = "Our leads are generated by highly trained tele-sales professionals",
                     PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                    //Payment Area  || Stripe?
                     AcceptsCredit = true,
                     CreditComments = "We accept Credit",
                     AcceptsDebit = true,
                    DebitComments = "We accept Debit",
                     AcceceptsAmericanExpress = true,
                    AmericanExpressComments = "We accept American Express",
                     AcceptsPaypal = true,
                    PaypalEmailAddress = "joeLeads@leads.com",
                    PaypalComments ="We accept Paypal",
                     AcceptsMoneyOrder = true,
                    MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                     AcceptsVenmo = true,
                     VenmoComments = "Maximum transaction amount $675",
                    VenmoHandle = "JoesLeadsNow",

                    CompanyRating = 




                },

                 new Company
                {
                     CompanyID = 3,
                     UserID = 3,
                    IsArchived = false,
                    IndustryID = 1,
                     CompanyName = "All Star Lead Company",
                     Address1 = "111 Hollwood Blvd",
                     Address2 = "Suite: 880",
                     State = "CA",
                     City = "Los Angeles",
                     Zip = "90036",
                     TelephoneNumber = "5553331234",
                     OtherTelephoneNumber = "5551231234",
                     EmailAddress  = "Joe@leads.com",
                     SkypeHandle = "LeadCo",
                WebsiteURL = "http://www.leadcompany.com",
                     PictureLogoURL = "http://design.ubuntu.com/wp-content/uploads/ubuntu-logo32.png",
                     Bio = "The best lead company ever.  Like a pheonix we rise from the ashes.",
                     LeadNotes = "Our leads are generated by highly trained tele-sales professionals",
                     PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                    //Payment Area  || Stripe?
                     AcceptsCredit = true,
                     CreditComments = "We accept Credit",
                     AcceptsDebit = true,
                    DebitComments = "We accept Debit",
                     AcceceptsAmericanExpress = true,
                    AmericanExpressComments = "We accept American Express",
                     AcceptsPaypal = true,
                    PaypalEmailAddress = "joeLeads@leads.com",
                    PaypalComments ="We accept Paypal",
                     AcceptsMoneyOrder = true,
                    MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                     AcceptsVenmo = true,
                     VenmoComments = "Maximum transaction amount $675",
                    VenmoHandle = "JoesLeadsNow",

                    CompanyRating =


            }

        }
    }
}
