using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using ReviewApplication.Core.Domain;
using ReviewApplication.API.Controllers;
using ReviewApplication.Core.Infrastructure;
using ReviewApplication.Core.Repository;
using System.Linq;
using System.Collections.ObjectModel;
using System.Web.Http;
using System.Web.Http.Results;
using ReviewApplication.Core.Models;
using System.Net;
using System.Linq.Expressions;

namespace ReviewApplication.API.Test.ReviewApplication
{
    [TestClass]
    public class ReviewPostsControllerTests
    {
        private Mock<IReviewPostRepository> _reviewPostRepositoryMock;
        private Mock<ICompanyRepository> _companyRepositoryMock;
        private Mock<IInsuranceAgentRepository> _insuranceAgentRepositoryMock;
        private Mock<ILeadProductRepository> _leadProductRepositoryMock;
        private Mock<IUnitOfWork> _unitOfWorkMock;

        private ReviewPostsController _controller;
        private ReviewPost[] _reviewPosts;
        private InsuranceAgent[] _insuranceAgents;
        private Company[] _companies;
        private LeadProduct[] _leadProducts;




        [TestInitialize]
        public void Inialize()
        {
            //Setup AutoMapper
            WebApiConfig.SetupAutomapper();

            //Setup Respositories
            _insuranceAgentRepositoryMock = new Mock<IInsuranceAgentRepository>();
            _leadProductRepositoryMock = new Mock<ILeadProductRepository>();
            _reviewPostRepositoryMock = new Mock<IReviewPostRepository>();
            _companyRepositoryMock = new Mock<ICompanyRepository>();

            //Build Review Posts Below



            _companies = new[]
            {
                //Test Company 1
                new Company
                {
                     CompanyID = 1,
                     UserID = 1,
                     IsArchived = false,
                     CompanyName = "Joe Schmoes Lead Company",
                     Address1 = "101 Wonder Way",
                     Address2 = "Suite: 290",
                     State = "CA",
                     City = "Los Angeles",
                     Zip = "90036",
                     TelephoneNumber = "5553331234",
                     OtherTelephoneNumber = "5551231234",
                     EmailAddress  = "Joe@leads.com",
                     SkypeHandle = "LeadCo",
                     WebsiteURL = "http://www.leadcompany.com",
                     PictureLogoURL = "https://lh5.ggpht.com/E3EDtjhawNHXNOhnid79xqMofjwy6wIciqHC_-Xe77F9HhPfDOYaJLFTyGBYsDeHvQ=w300",
                     Bio = "The best lead company ever.  Like a pheonix we rise from the ashes.",
                     LeadNotes = "Our leads are generated by highly trained tele-sales professionals",
                     PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                    //Payment Area  || Stripe?
                     AcceptsCredit = true,
                     CreditComments = "We accept Credit",
                     AcceptsDebit = true,
                     DebitComments = "We accept Debit",
                     AcceceptsAmericanExpress = true,
                     AmericanExpressComments = "We accept American Express",
                     AcceptsPaypal = true,
                     PaypalEmailAddress = "joeLeads@leads.com",
                     PaypalComments ="We accept Paypal",
                     AcceptsMoneyOrder = true,
                     MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                     AcceptsVenmo = true,
                     VenmoComments = "Maximum transaction amount $675",
                     VenmoHandle = "JoesLeadsNow",

                     ReviewPosts = _reviewPosts.Where(rp => rp.CompanyID == 1).ToArray(),
                     LeadProducts = _leadProducts.Where(lp => lp.CompanyID == 1).ToArray()
                },

                //Test Company 2
                 new Company
                {
                     CompanyID = 3,
                     UserID = 3,
                     IsArchived = false,
                     CompanyName = "All Star Leads Company",
                     Address1 = "111 Hollwood Blvd",
                     Address2 = "Suite: 880",
                     State = "CA",
                     City = "Los Angeles",
                     Zip = "90036",
                     TelephoneNumber = "5556667894",
                     OtherTelephoneNumber = "5557891234",
                     EmailAddress  = "leads@allstarleads.com",
                     SkypeHandle = "AllStarLeads",
                     WebsiteURL = "http://www.AllStarleads.com",
                     PictureLogoURL = "http://design.ubuntu.com/wp-content/uploads/ubuntu-logo32.png",
                     Bio = "All Star Leads Company.  Our leads are 5-star!",
                     LeadNotes = "All of our leads are organic and come with a contact gurantee!",
                     PaymentNotes = "Please wait 2 days for payment to clear before lead generation begins",

                    //Payment Area  || Stripe?
                     AcceptsCredit = true,
                     CreditComments = "We accept Credit",
                     AcceptsDebit = true,
                     DebitComments = "We accept Debit",
                     AcceceptsAmericanExpress = true,
                     AmericanExpressComments = "We accept American Express",
                     AcceptsPaypal = true,
                     PaypalEmailAddress = "leads@allstarleads.com",
                     PaypalComments ="We accept Paypal",
                     AcceptsMoneyOrder = true,
                     MoneyOrderComments = "Please allow 2 weeks for money order to arrive",
                     AcceptsVenmo = true,
                     VenmoComments = "We accept Venmo!",
                     VenmoHandle = "AllStarLeads",

                     ReviewPosts = _reviewPosts.Where(rp => rp.CompanyID == 3).ToArray(),
                     LeadProducts = _leadProducts.Where(lp => lp.CompanyID == 3).ToArray()
                 }
            };


            _leadProducts = new[]
           {
                //Lead Product for Test Company 1
                new LeadProduct
                {
                    LeadProductID = 0,
                    CompanyID = 1,
                    IsArchived = false,
                    Price = 20,
                    ProductNotes = "Price is per telemarketing lead generated",
                    OrderLink = "http://www.google.com",
                    TelemarketingLead = true,
                    TelemarketingLeadNotes = "Leads will be generated within 2 weeks of order date",
                    MailLead = false,
                    MailLeadLeadNotes = "",
                    Press1Lead = false,
                    Press1LeadNotes = "",
                    InternetLead = false,
                    InternetLeadNotes = "",
                    ColdCallPhoneNumberList = false,
                    ColdCallPhoneNumberListLeadNotes = ""
                },

                //Lead Product for Test Company 1
                new LeadProduct
                {
                     LeadProductID = 1,
                     CompanyID = 1,
                     IsArchived = false,
                     Price = 15,
                     ProductNotes = "Price is per Press-1 Lead Generated",
                     OrderLink = "http://wwww.google.com",
                     TelemarketingLead = false,
                     TelemarketingLeadNotes = "",
                     MailLead = false,
                     MailLeadLeadNotes = "",
                     Press1Lead = true,
                     Press1LeadNotes = "Leads will be generated within 2 weeks of Order date",
                     InternetLead = false,
                     InternetLeadNotes = "",
                     ColdCallPhoneNumberList = false,
                     ColdCallPhoneNumberListLeadNotes = ""
                },

                //Lead Product for Test Company 2
                new LeadProduct
                {
                     LeadProductID = 2,
                     CompanyID = 3,
                     IsArchived = false,
                     Price = 25,
                     ProductNotes = "Price per Telemarketing Lead Generated",
                     OrderLink = "http://wwww.google.com",
                     TelemarketingLead = true,
                     Press1LeadNotes = "",
                     MailLead = false,
                     MailLeadLeadNotes = "",
                     Press1Lead = true,
                     TelemarketingLeadNotes = "Leads will be generated within 2 weeks of Order date",
                     InternetLead = false,
                     InternetLeadNotes = "",
                     ColdCallPhoneNumberList = false,
                     ColdCallPhoneNumberListLeadNotes = ""
                },

                //Lead Product for Test Company 2
                new LeadProduct
                {
                     LeadProductID = 3,
                     CompanyID = 3,
                     IsArchived = false,
                     Price = 15,
                     ProductNotes = "Price is per Press-1 Lead Generated",
                     OrderLink = "http://wwww.google.com",
                     TelemarketingLead = false,
                     TelemarketingLeadNotes = "",
                     MailLead = false,
                     MailLeadLeadNotes = "",
                     Press1Lead = true,
                     Press1LeadNotes = "Leads will be generated within 2 weeks of Order date",
                     InternetLead = false,
                     InternetLeadNotes = "",
                     ColdCallPhoneNumberList = false,
                     ColdCallPhoneNumberListLeadNotes = ""
                }
            };

            _reviewPosts = new[]
            {
                //Review Post for Test company 1
                new ReviewPost
                {
                    ReviewPostID = 0,
                    CompanyID = 1,
                    InsuranceAgentID = 0,
                    LeadProductID = 0,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,3,10,55,32),
                    CompanyRating = 5,
                    PostTitle = "Great Company and Customer Service!",
                    PostBody = "I recieved my leads within 10 days of ordering. I converted 10 of the 20 leads and I am very happy",
                    NumberOfLikes = 2

                },

                 //Review Post for Test company 1
                new ReviewPost
                {
                    ReviewPostID = 1,
                    CompanyID = 1,
                    InsuranceAgentID = 1,
                    LeadProductID = 0,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,4,10,55,32),
                    CompanyRating = 3,
                    PostTitle = "Quality Leads",
                    PostBody = "Very high quality! I called 20 very happy clients!",
                    NumberOfLikes = 1
                },

                 //Review Post for Test company 1
                new ReviewPost
                {
                    ReviewPostID = 2,
                    CompanyID = 1,
                    InsuranceAgentID = 2,
                    LeadProductID = 0,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,4,11,55,32),
                    CompanyRating = 5,
                    PostTitle = "Fantastic leads",
                    PostBody = "Great Customer service! 2 of my leads were bad and they reimbursed me immediately!",
                    NumberOfLikes = 2
                },

                 //Review Post for Test company 2
                 new ReviewPost
                {
                    ReviewPostID = 3,
                    CompanyID = 3,
                    InsuranceAgentID = 3,
                    LeadProductID = 2,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,3,10,55,32),
                    CompanyRating = 2,
                    PostTitle = "Not the best leads",
                    PostBody = "Alright leads for the price, many of my clients were confused when I called them. 2/5",
                    NumberOfLikes = 3
                },

                  //Review Post for Test company 2
                 new ReviewPost
                {
                    ReviewPostID = 4,
                    CompanyID = 3,
                    InsuranceAgentID = 4,
                    LeadProductID = 2,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,3,11,55,32),
                    CompanyRating = 4,
                    PostTitle = "Quick Leads",
                    PostBody = "Great Leads!  High Conversion Rate!",
                    NumberOfLikes = 2
                },

                  //Review Post for Test company 2
                 new ReviewPost
                {
                    ReviewPostID = 5,
                    CompanyID = 3,
                    InsuranceAgentID = 5,
                    LeadProductID = 2,
                    IsArchived = false,
                    ReviewPostDate = new DateTime(2015,12,3,12,55,32),
                    CompanyRating = 4,
                    PostTitle = "Decent Leads!",
                    PostBody = "No Complaints!  Will use again",
                    NumberOfLikes = 0,
                },

            };

            //Setup Mock LeadProduct Repository
            _leadProductRepositoryMock.Setup(lp => lp.GetAll()).Returns(_leadProducts.AsQueryable());
            _leadProductRepositoryMock.Setup(lp => lp.GetByID(0)).Returns(_leadProducts[0]);
            _leadProductRepositoryMock.Setup(lp => lp.GetByID(1)).Returns(_leadProducts[1]);
            _leadProductRepositoryMock.Setup(lp => lp.GetByID(2)).Returns(_leadProducts[2]);
            _leadProductRepositoryMock.Setup(lp => lp.GetByID(3)).Returns(_leadProducts[3]);

            //Setup Mock ReviewPost Repository
            _reviewPostRepositoryMock.Setup(rp => rp.GetAll()).Returns(_reviewPosts.AsQueryable());
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(0)).Returns(_reviewPosts[0]);
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(1)).Returns(_reviewPosts[1]);
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(2)).Returns(_reviewPosts[2]);
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(3)).Returns(_reviewPosts[3]);
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(4)).Returns(_reviewPosts[4]);
            _reviewPostRepositoryMock.Setup(rp => rp.GetByID(5)).Returns(_reviewPosts[5]);



            //Setup Mock Company Repository
            _companyRepositoryMock.Setup(cr => cr.GetAll()).Returns(_companies.AsQueryable());
            _companyRepositoryMock.Setup(cr => cr.GetByID(1)).Returns(_companies[0]);
            _companyRepositoryMock.Setup(cr => cr.GetByID(3)).Returns(_companies[1]);

            // Set up unit of work and controller
            _unitOfWorkMock = new Mock<IUnitOfWork>();

            _controller = new ReviewPostsController(_reviewPostRepositoryMock.Object, _unitOfWorkMock.Object);
        }



        [TestMethod] // [0]
        public void GetReviewPostsReturnReviewPosts()
        {
            //Arrange

            //Act
            var reviewPosts = _controller.GetReviewPosts();

            //Assert
            _reviewPostRepositoryMock.Verify(rp => rp.GetAll(), Times.Once);
            Assert.AreEqual(reviewPosts.Count(), 6);
        }

        [TestMethod] // [1]
        public void GetReviewPostByIDReturnReviewPost()
        {
            //Arrange

            //Act
            IHttpActionResult actionResult = _controller.GetReviewPost(1);

            //Assert
            _reviewPostRepositoryMock.Verify(rp => rp.GetByID(1), Times.Once);
            Assert.IsInstanceOfType(actionResult, typeof(OkNegotiatedContentResult<ReviewPostModel>));
            
        }



        [TestMethod] // [2]
        public void GetAllReviewPostsByCompanyID()
        {
            //TODO: Check Logic Here
            //Arrange
            _reviewPostRepositoryMock.Setup(rp => rp.Where(It.IsAny<Expression<Func<ReviewPost, bool>>>()))
                            .Returns(_reviewPosts.Where(rp => rp.Company.CompanyID.Equals(1)).AsQueryable());

            //Act
            var reviewPostQuery = _controller.GetAllReviewPostsForCompany(1);

            //Assert
            _reviewPostRepositoryMock.Verify(rpr => rpr.GetAll(), Times.Once);
            Assert.AreEqual(reviewPostQuery.Count(), 3);

        }


        [TestMethod] // [3]
        public void GetAllReviewPostsByInsuranceAgentID()
        {
            //TODO: Check Logic Here
            //Arrange
            _reviewPostRepositoryMock.Setup(rp => rp.Where(It.IsAny<Expression<Func<ReviewPost, bool>>>()))
                            .Returns(_reviewPosts.Where(rp => rp.InsuranceAgent.InsuranceAgentID.Equals(1)).AsQueryable());

            //Act
            var reviewPostQuery = _controller.GetAllReviewPostsForInsuranceAgent(1);

            //Assert
            _reviewPostRepositoryMock.Verify(rpr => rpr.GetAll(), Times.Once);
            Assert.AreEqual(reviewPostQuery.Count(), 1);

        }

        [TestMethod] // [4]
        public void GetAllReviewPostsByLeadProductID()
        {
            //Arrange
            _reviewPostRepositoryMock.Setup(rp => rp.Where(It.IsAny<Expression<Func<ReviewPost, bool>>>()))
                            .Returns(_reviewPosts.Where(rp => rp.LeadProductID.Equals(1)).AsQueryable());

            //Act
            var reviewPostQuery = _controller.GetAllReviewPostsForLeadProduct(0);

            //Assert
            _reviewPostRepositoryMock.Verify(rpr => rpr.GetAll(), Times.Once);
            Assert.AreEqual(reviewPostQuery.Count(), 3);

        }

        [TestMethod] //[5]
        public void PutLeadProductReturnLeadProduct()
        {
            //Arrange

            //Act
            IHttpActionResult actionResult =
                _controller.PutReviewPost(
                    0,
                    new ReviewPostModel
                    {
                        ReviewPostID = 0,
                        IsArchived = false

                    });
            var statusCodeResult = actionResult as StatusCodeResult;

            //Assert
            _reviewPostRepositoryMock.Verify(rp => rp.GetByID(0), Times.Once);
            _reviewPostRepositoryMock.Verify(rp => rp.Update(It.IsAny<ReviewPost>()));

        }

        [TestMethod] //[6]
        public void PostLeadProductReturnLeadProduct()
        {
            //Arrange

            //Act
            IHttpActionResult actionResult = _controller.DeleteReviewPost(1);

            //Assert
            _reviewPostRepositoryMock.Verify(lp => lp.GetByID(1), Times.Once);
            _reviewPostRepositoryMock.Verify(lp => lp.Update(It.IsAny<ReviewPost>()), Times.Once);
            _unitOfWorkMock.Verify(uow => uow.Commit(), Times.Once);
            Assert.IsInstanceOfType(actionResult, typeof(OkNegotiatedContentResult<ReviewPost>));
            var contentResult = actionResult as OkNegotiatedContentResult<ReviewPostModel>;
            Assert.IsNotNull(contentResult);
            Assert.IsNotNull(contentResult.Content);
            Assert.IsTrue(contentResult.Content.ReviewPostID == 1);
        }

    }
}
